name : first action

on :
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-18.04
    steps:
      - name : gin application 
        run : echo "gin application"
        

       
