#for maintaining the code 
name : lint-go-code 
on : 
  push :
    branches :
      - main

jobs:
  lints:
    runs-on : ubuntu-latest
    steps : 
      - uses : actions/checkout@v2
      - uses : actions/setup-go@v2
        with : 
          stable : 'false'
          go-version : '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          skip-cache: true

      # - name : lint
      #   run : |
      #     curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/main/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
      # - name: Add golangci-lint to PATH
      #   run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify golangci-lint installation
        run: |
          which golangci-lint
          golangci-lint --version

      - name: Run linter
        run: golangci-lint run --verbose

          

