#for maintaining the code 
name : lint-go-code 
on : 
  push :
    branches :
      - main

jobs:
  lints:
    runs-on : ubuntu-latest
    steps : 
      - uses : actions/checkout@v2
      - uses : actions/setup-go@v2
        with : 
          stable : 'false'
          go-version : '1.21'

      - name : lint
        run : |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/main/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
          golangci-lint run  
#          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/main/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0


          

